In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Setup completed")
print(torch.__version__)

Setup completed
2.0.1+cpu


## Introduction to tensors

### Creating tensors
- Pytorch tensors are created using torch.Tensor() = [Pytorch.tensor](https://pytorch.org/docs/stable/tensors.html)
- 


In [2]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
# dimension of scalar
scalar.ndim

0

In [4]:
# item in the current scalar run time
scalar.item()

7

In [5]:
# vector

vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([
    [7,8],
    [9,8]
])
print(MATRIX)

tensor([[7, 8],
        [9, 8]])


In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([9, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([
    [
        [1,2,3],
        [2,3,4],
        [5,8,7]
        
    ]
        
])

print(TENSOR)

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 8, 7]]])


In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 8, 7]])

Upper TENSOR.shape represents that we have one 3,3 tensor

In [16]:
# random tensor with size with shape (3,4)
random_tensor = torch.rand(3,5)
print(random_tensor)

tensor([[0.3695, 0.1515, 0.7055, 0.0280, 0.2145],
        [0.9486, 0.5979, 0.3409, 0.7170, 0.0293],
        [0.3902, 0.4836, 0.6350, 0.5610, 0.0025]])


In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 5])

In [19]:
random_tensor1 = torch.rand(10, 20, 40)
random_tensor1

tensor([[[0.0760, 0.3880, 0.2902,  ..., 0.9668, 0.1024, 0.1928],
         [0.0085, 0.0469, 0.4483,  ..., 0.0494, 0.2993, 0.2640],
         [0.8090, 0.9896, 0.8870,  ..., 0.4376, 0.3024, 0.6181],
         ...,
         [0.0848, 0.5408, 0.2022,  ..., 0.9443, 0.6206, 0.9900],
         [0.0889, 0.9387, 0.2347,  ..., 0.9238, 0.4251, 0.5420],
         [0.9954, 0.8912, 0.3921,  ..., 0.9829, 0.8375, 0.5400]],

        [[0.9608, 0.3903, 0.5862,  ..., 0.6923, 0.4318, 0.3247],
         [0.4762, 0.7621, 0.3090,  ..., 0.9512, 0.4997, 0.4395],
         [0.8785, 0.8243, 0.0901,  ..., 0.6048, 0.5929, 0.4260],
         ...,
         [0.2030, 0.3783, 0.6631,  ..., 0.2283, 0.1743, 0.4601],
         [0.8002, 0.5744, 0.3591,  ..., 0.5788, 0.4170, 0.5857],
         [0.8087, 0.7570, 0.2321,  ..., 0.9014, 0.8919, 0.1218]],

        [[0.9936, 0.7999, 0.5806,  ..., 0.1361, 0.3633, 0.8018],
         [0.0427, 0.1610, 0.5550,  ..., 0.0075, 0.4679, 0.2210],
         [0.7628, 0.5738, 0.5387,  ..., 0.8974, 0.7324, 0.

In [20]:
random_tensor1.ndim

3

In [21]:
# create a random tensor with smilar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,223,3)) # height , width , color channels (R,G.B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 223, 3]), 3)

In [22]:
# create a random tensor with smilar shape to an image tensor

random_image_size_tensor = torch.rand(size=(2233,2453,3)) # height , width , color channels (R,G.B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([2233, 2453, 3]), 3)

# Zeros and ones

In [23]:
# create a tensor of all zeros

zero_tensors = torch.zeros(size=(9,9))
zero_tensors

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
# create a tensor of all ones
ones =  torch.ones(size=(9,9))

ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
ones*zero_tensors

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### create a tensor with range of tensors and tensor-like

In [26]:
# Use torch.range

range_tensor = torch.range(0,10)
range_tensor

/tmp/ipykernel_3305/1374888573.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
# a range

aranget = torch.arange(start=0, end=1000, step=87)
aranget

tensor([  0,  87, 174, 261, 348, 435, 522, 609, 696, 783, 870, 957])

In [28]:
# creating tensor like

zeros = torch.zeros_like(input=aranget)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# tesnor data types

# Float 32 tensor
float_32_tensor = torch.tensor([2.9,4.1,9.0], 
                               
                               dtype=torch.float16, #datatype of the current allocated tensor is set to 16 bit floating integer number
                               
                               device=None, # what device your tensor on
                               
                               requires_grad=False # wheather or not to track the gradient with this tensor operation
)

float_32_tensor

tensor([2.9004, 4.1016, 9.0000], dtype=torch.float16)

In [30]:
float_32_tensor.dtype

torch.float16

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2.9004, 4.1016, 9.0000], dtype=torch.float16)

In [32]:
# type casting or tensor typecasting
int_32_tensor = torch.tensor([3,4,9],dtype=torch.long)
int_32_tensor

tensor([3, 4, 9])

### Getting information from tensors

1. Tensors are not right data type = to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor is not right shape = to get shape from a tensor , can use `tensor.shape`
3. tensor not on the right device = to get device from a tensor , can use `tensor.device`

In [33]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4068, 0.5389, 0.1005, 0.1019],
        [0.0950, 0.9778, 0.6108, 0.6940],
        [0.6690, 0.9524, 0.8076, 0.5627]])

In [34]:
#Findout details of some tensor
print(some_tensor)
print(f"data type of tensor: {some_tensor.dtype}")

tensor([[0.4068, 0.5389, 0.1005, 0.1019],
        [0.0950, 0.9778, 0.6108, 0.6940],
        [0.6690, 0.9524, 0.8076, 0.5627]])
data type of tensor: torch.float32


In [35]:
# shape of the tensor
print(f"Shape of the tensor {some_tensor.shape}") 

Shape of the tensor torch.Size([3, 4])


In [36]:
# size of the tensor

print(f"Size of the tensor {some_tensor.size()}")

Size of the tensor torch.Size([3, 4])


In [37]:
# device finder

print(f"device on which the tensor is running {some_tensor.device}")

device on which the tensor is running cpu


## Manipulating Tensors (Tensor operations)

Tensor operations include :

* Addition
* Subtraction
* Multiplication (element- wise)
* Division
* Matrix Multiplication


In [38]:
# create a tensor with addition
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [39]:
# mltiply tensor

tensor * 10

tensor([10, 20, 30])

In [40]:
# subtract

tensor - 10

tensor([-9, -8, -7])

In [41]:
# tryout  pytorch in-build functions
torch.mul(tensor,46)


tensor([ 46,  92, 138])

In [42]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor  * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [44]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.63 ms, sys: 556 µs, total: 2.18 ms
Wall time: 1.42 ms


In [45]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 295 µs, sys: 101 µs, total: 396 µs
Wall time: 321 µs


tensor(14)

### Matrix multiplication

Two main ways of performing multiplication is neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication


There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the outer dimension

* `(2,3) @ (3,2)` - >  `(2,2)`
* `(3,2) @ (2,3)` - > `(3,3)`

In [46]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([
    [1,2],
    [3,6],
    [4,5]])
tensor_B = torch.tensor([
    [7,8],
    [9,11],
    [12,13]])

torch.matmul(tensor_A, tensor_B)

We can fix the shape of the current tensor shape using **Transpose**

A **transpose** switches the axis or dimensions of a given tensor.

In [ ]:
tensor_B.T

In [ ]:
tensor_B.T.shape

In [ ]:
torch.mm(tensor_A, tensor_B.T)

In [ ]:
# The matrix tmultiplication operation works when tensor_B is transposed

print(f"origin shapes: tensor_A {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above ), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\Output shape: {output.shape}")


torch.mm(tensor_A, tensor_B.T).shape

## Finding the min. max , mean , sum , etc(tensor aggregation)

In [ ]:
# create a tensor

x = torch.arange(0, 100, 10)
x

In [ ]:
torch.min(x), torch.max(x)

In [ ]:
# finding the mean - note: the torch.mean() function requires a tensor of float or long datatype to work
torch.mean(x.type(torch.float16))

In [ ]:
#find the sum

torch.sum(x)

## find the positional mean and max

In [ ]:
x

In [ ]:
# find the position in  tensor that has minimum arg min 
x.argmin()

In [ ]:
x[0]

In [ ]:
# find the [psotopm om the tensor that has mximum arg maxx.arg]
x.argmax()

In [ ]:
x[9]

## Reshaping, statcking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to define shape
* View - Return a view of an input tensor of certain shape but keep the shape memory as original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side
  [hstatck]
  * Squeeze - remove all `1` dimension to a target tensor
  * Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [48]:
# let's create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [51]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Changing z change x (because a view of tensor shares the same memory as the origin input)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))