In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Setup completed")
print(torch.__version__)

Setup completed
2.0.1+cpu


## Introduction to tensors

### Creating tensors
- Pytorch tensors are created using torch.Tensor() = [Pytorch.tensor](https://pytorch.org/docs/stable/tensors.html)
- 


In [2]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
# dimension of scalar
scalar.ndim

0

In [4]:
# item in the current scalar run time
scalar.item()

7

In [5]:
# vector

vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([
    [7,8],
    [9,8]
])
print(MATRIX)

tensor([[7, 8],
        [9, 8]])


In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([9, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([
    [
        [1,2,3],
        [2,3,4],
        [5,8,7]
        
    ]
        
])

print(TENSOR)

tensor([[[1, 2, 3],
         [2, 3, 4],
         [5, 8, 7]]])


In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 8, 7]])

Upper TENSOR.shape represents that we have one 3,3 tensor

In [16]:
# random tensor with size with shape (3,4)
random_tensor = torch.rand(3,5)
print(random_tensor)

tensor([[0.0300, 0.6212, 0.0705, 0.7958, 0.5339],
        [0.4552, 0.0565, 0.2903, 0.2970, 0.9088],
        [0.1395, 0.3215, 0.8547, 0.0629, 0.4627]])


In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 5])

In [19]:
random_tensor1 = torch.rand(10, 20, 40)
random_tensor1

tensor([[[0.3918, 0.7487, 0.2162,  ..., 0.7359, 0.8667, 0.1385],
         [0.0728, 0.0119, 0.0469,  ..., 0.8173, 0.9848, 0.2977],
         [0.1290, 0.1871, 0.1090,  ..., 0.8421, 0.2353, 0.4112],
         ...,
         [0.2067, 0.2112, 0.4464,  ..., 0.0809, 0.0592, 0.5580],
         [0.3293, 0.5224, 0.3892,  ..., 0.2698, 0.9589, 0.0312],
         [0.7444, 0.6643, 0.7724,  ..., 0.2650, 0.2603, 0.1073]],

        [[0.2960, 0.8123, 0.9801,  ..., 0.2686, 0.5600, 0.3316],
         [0.8501, 0.5663, 0.2512,  ..., 0.2993, 0.8214, 0.7142],
         [0.5946, 0.0182, 0.8162,  ..., 0.2477, 0.7702, 0.5040],
         ...,
         [0.2146, 0.5880, 0.5868,  ..., 0.0334, 0.2282, 0.8569],
         [0.3409, 0.1373, 0.3308,  ..., 0.8913, 0.6929, 0.8422],
         [0.2256, 0.7533, 0.6940,  ..., 0.6841, 0.5218, 0.5275]],

        [[0.8100, 0.5094, 0.2844,  ..., 0.7686, 0.8933, 0.5496],
         [0.9970, 0.8584, 0.7287,  ..., 0.3164, 0.5485, 0.8460],
         [0.8872, 0.3157, 0.3946,  ..., 0.5044, 0.7448, 0.

In [20]:
random_tensor1.ndim

3

In [21]:
# create a random tensor with smilar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,223,3)) # height , width , color channels (R,G.B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 223, 3]), 3)

In [22]:
# create a random tensor with smilar shape to an image tensor

random_image_size_tensor = torch.rand(size=(2233,2453,3)) # height , width , color channels (R,G.B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([2233, 2453, 3]), 3)

# Zeros and ones

In [23]:
# create a tensor of all zeros

zero_tensors = torch.zeros(size=(9,9))
zero_tensors

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
# create a tensor of all ones
ones =  torch.ones(size=(9,9))

ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
ones*zero_tensors

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### create a tensor with range of tensors and tensor-like

In [26]:
# Use torch.range

range_tensor = torch.range(0,10)
range_tensor

/tmp/ipykernel_4750/1374888573.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
# a range

aranget = torch.arange(start=0, end=1000, step=87)
aranget

tensor([  0,  87, 174, 261, 348, 435, 522, 609, 696, 783, 870, 957])

In [28]:
# creating tensor like

zeros = torch.zeros_like(input=aranget)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# tesnor data types

# Float 32 tensor
float_32_tensor = torch.tensor([2.9,4.1,9.0], 
                               
                               dtype=torch.float16, #datatype of the current allocated tensor is set to 16 bit floating integer number
                               
                               device=None, # what device your tensor on
                               
                               requires_grad=False # wheather or not to track the gradient with this tensor operation
)

float_32_tensor

tensor([2.9004, 4.1016, 9.0000], dtype=torch.float16)

In [30]:
float_32_tensor.dtype

torch.float16

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2.9004, 4.1016, 9.0000], dtype=torch.float16)

In [32]:
# type casting or tensor typecasting
int_32_tensor = torch.tensor([3,4,9],dtype=torch.long)
int_32_tensor

tensor([3, 4, 9])

### Getting information from tensors

1. Tensors are not right data type = to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor is not right shape = to get shape from a tensor , can use `tensor.shape`
3. tensor not on the right device = to get device from a tensor , can use `tensor.device`

In [33]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4091, 0.2765, 0.1499, 0.8780],
        [0.1867, 0.1291, 0.9262, 0.1874],
        [0.8258, 0.6627, 0.9046, 0.5186]])

In [34]:
#Findout details of some tensor
print(some_tensor)
print(f"data type of tensor: {some_tensor.dtype}")

tensor([[0.4091, 0.2765, 0.1499, 0.8780],
        [0.1867, 0.1291, 0.9262, 0.1874],
        [0.8258, 0.6627, 0.9046, 0.5186]])
data type of tensor: torch.float32


In [35]:
# shape of the tensor
print(f"Shape of the tensor {some_tensor.shape}") 

Shape of the tensor torch.Size([3, 4])


In [36]:
# size of the tensor

print(f"Size of the tensor {some_tensor.size()}")

Size of the tensor torch.Size([3, 4])


In [37]:
# device finder

print(f"device on which the tensor is running {some_tensor.device}")

device on which the tensor is running cpu


## Manipulating Tensors (Tensor operations)

Tensor operations include :

* Addition
* Subtraction
* Multiplication (element- wise)
* Division
* Matrix Multiplication


In [38]:
# create a tensor with addition
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [39]:
# mltiply tensor

tensor * 10

tensor([10, 20, 30])

In [40]:
# subtract

tensor - 10

tensor([-9, -8, -7])

In [41]:
# tryout  pytorch in-build functions
torch.mul(tensor,46)


tensor([ 46,  92, 138])

In [42]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor  * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [44]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.24 ms, sys: 602 µs, total: 2.84 ms
Wall time: 1.96 ms


In [45]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 414 µs, sys: 111 µs, total: 525 µs
Wall time: 430 µs


tensor(14)

### Matrix multiplication

Two main ways of performing multiplication is neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication


There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the outer dimension

* `(2,3) @ (3,2)` - >  `(2,2)`
* `(3,2) @ (2,3)` - > `(3,3)`

In [46]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([
    [1,2],
    [3,6],
    [4,5]])
tensor_B = torch.tensor([
    [7,8],
    [9,11],
    [12,13]])

torch.matmul(tensor_A, tensor_B)

We can fix the shape of the current tensor shape using **Transpose**

A **transpose** switches the axis or dimensions of a given tensor.

In [ ]:
tensor_B.T

In [ ]:
tensor_B.T.shape

In [ ]:
torch.mm(tensor_A, tensor_B.T)

In [ ]:
# The matrix tmultiplication operation works when tensor_B is transposed

print(f"origin shapes: tensor_A {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above ), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\Output shape: {output.shape}")


torch.mm(tensor_A, tensor_B.T).shape

## Finding the min. max , mean , sum , etc(tensor aggregation)

In [ ]:
# create a tensor

x = torch.arange(0, 100, 10)
x

In [ ]:
torch.min(x), torch.max(x)

In [ ]:
# finding the mean - note: the torch.mean() function requires a tensor of float or long datatype to work
torch.mean(x.type(torch.float16))

In [ ]:
#find the sum

torch.sum(x)

## find the positional mean and max

In [ ]:
x

In [ ]:
# find the position in  tensor that has minimum arg min 
x.argmin()

In [ ]:
x[0]

In [ ]:
# find the [psotopm om the tensor that has mximum arg maxx.arg]
x.argmax()

In [ ]:
x[9]

## Reshaping, statcking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to define shape
* View - Return a view of an input tensor of certain shape but keep the shape memory as original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side
  [hstatck]
  * Squeeze - remove all `1` dimension to a target tensor
  * Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [52]:
# let's create a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [55]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
# Changing z change x (because a view of tensor shares the same memory as the origin input)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
# Stack tensors on top of each other 

x_stacked  = torch.stack([x,x,x,x], dim=1) # it only supports single dimmension

x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
# torch.squeeze() - remove all single dimensions from a targate tensor

x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))

In [65]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped

x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")

print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [60]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
# torch unsqeeze - adds a signle dimension to a target tensor at a specific dim (dimension)

print(f"Squeezed version of the tensor -> {x_squeezed}")

print(f"Previous target : {x_squeezed}")

print(f"Previous shape: {x_squeezed.shape}")


# Add an extra dimension with unsqeezed

x_unsquzeed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsquzeed}")

print(f"New shape: {x_unsquzeed.shape}")


Squeezed version of the tensor -> tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [72]:
# torch.permute - rearrages the dimensons of a target tensor in a specified order

x_original = torch.randn(size=(224,224,3)) # [height, width, color_channels]
x_original

# Permute the origin tensor to rearrange the axis (or dim)

x_permuted = x_original.permute(2,0,1) # shifts  axis 0-> 1, 1->2 , 2->0

print(f"previous shape -> {x_original.shape}")

print(f"\nNew permuted shape -> {x_permuted.shape}") # [color channels , height , width]

previous shape -> torch.Size([224, 224, 3])

New permuted shape -> torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy

In [4]:
# creating a tensor

import torch

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [5]:
# index on new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# Index on the middle bracket 

x[0][0]

tensor([1, 2, 3])

In [7]:
# indexing on most inner bracket (last dimmension)

x[0][0][0]

tensor(1)

In [9]:
# finding number 9 using manual indexing
x[0][2][2] # here 0 is the total dim of the matrix or the singular matrix and there after row wise and on [2] index there is our target  out and there after on [2] position on [x] axis element will be 9 

tensor(9)

In [88]:
# You can also use ":" to select "all" of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [10]:
# Get all values of 0 th and 1st dimensions but ony index 1 of 2 dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [11]:
# get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension

x[:,1,1]

tensor([5])

In [13]:
x[0,0,:]

tensor([1, 2, 3])

In [14]:
# index on x to return [3:6:9]

print(x[:,:,2])

tensor([[3, 6, 9]])


In [19]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflection numpy default datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
array.dtype

dtype('float64')

In [20]:
# change the value of an array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [22]:
# tensor to numpy array
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [23]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [24]:
# change the tensor, what happen to `numpy tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))